version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ads_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ads_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "ads_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/ads_db
      ML_SERVICE_URL: http://ml:8001/generate_text/
    depends_on:
      - postgres
    networks:
      - ads_network

  ml:
    build: ./ml_module
    ports:
      - "8001:8001"
    networks:
      - ads_network

volumes:
  postgres_data:

networks:
  ads_network:
